version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./services/postgresql:/var/lib/postgresql
    networks:
      - backend
    ports:
      - 5432
  api:
    image: hiddenalphabet-api-server
    networks:
      - backend
    ports:
      - 8080
    links:
      - postgres
    depends_on:
      - postgres
  nginx:
    image: nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/public:/var/www/html:ro
      - /etc/letsencrypt:/etc/letsencrypt/:ro
    networks:
      - backend
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    links:
      - api
    depends_on:
      - api

networks:
  backend: