version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./services/postgres:/var/lib/postgresql
    networks:
      - backend
    ports:
      - 5432
  setup:
    image: setup
    environment:
      - ENV=production
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USERNAME=api
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=api
    build: ./services/postgres/setup
    networks:
      - backend
    links:
      - postgres
    depends_on:
      - postgres
  api:
    image: api
    environment:
      - ENV=production
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USERNAME=api
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=api
    build: ./services/api
    networks:
      - backend
    ports:
      - 8080
    links:
      - postgres
    depends_on:
      - setup
  nginx:
    image: nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/public:/var/www/html:ro
      - ./services/nginx/public/assets/:/var/www/assets:ro
      - /etc/letsencrypt:/etc/letsencrypt/:ro
    networks:
      - backend
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    links:
      - api
    depends_on:
      - api

networks:
  backend:
