version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - $PWD/services/postgresql:/var/lib/postgresql
    networks:
      - backend
    ports:
      - 5432
  webserver:
    image: infrastructureascode/hello-world
    networks:
      - backend
    ports:
      - 8080
    links:
      - postgres
    depends_on:
      - postgres
  nginx:
    image: nginx
    volumes:
      - $PWD/services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/public:/var/www/html:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    networks:
      - backend
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    links:
      - webserver
    depends_on:
      - webserver

networks:
  backend:
